import dotenv from "dotenv";

import { iceCreamCategories, ingredientCategories } from "@/DB/schema";
import { drizzle } from "drizzle-orm/neon-http";

dotenv.config({
  path: "./.env.local",
});

const db = drizzle(process.env.DATABASE_URL);

async function seed() {
  const categories = [
    {
      name: "Gelato",
      sugarsMin: "16.00",
      sugarsMax: "22.00",
      fatsMin: "5.00",
      fatsMax: "12.00",
      msnfMin: "7.50",
      msnfMax: "11.50",
      otherSolidsMin: "0.00",
      otherSolidsMax: "5.00",
      totalSolidsMin: "35.00",
      totalSolidsMax: "40.00",
      podMin: "26.00",
      podMax: "31.00",
      fruitMin: "20.00",
      fruitMax: "40.00",
      alcoholMin: "1.00",
      alcoholMax: "2.00",
      overrunMin: "33.00",
      overrunMax: "35.00",
      groundFoodsMin: "5.00",
      groundFoodsMax: "10.00",
    },
    {
      name: "Sorbetto",
      sugarsMin: "20.00",
      sugarsMax: "32.00",
      fatsMin: "0.00",
      fatsMax: "4.00",
      msnfMin: "0.00",
      msnfMax: "2.00",
      otherSolidsMin: "0.00",
      otherSolidsMax: "5.00",
      totalSolidsMin: "25.00",
      totalSolidsMax: "35.00",
      podMin: "28.00",
      podMax: "35.00",
      fruitMin: "30.00",
      fruitMax: "60.00",
      alcoholMin: "1.00",
      alcoholMax: "2.00",
      overrunMin: "33.00",
      overrunMax: "35.00",
      groundFoodsMin: "5.00",
      groundFoodsMax: "10.00",
    },
    {
      name: "Granita",
      sugarsMin: "15.00",
      sugarsMax: "20.00",
      fatsMin: "0.00",
      fatsMax: "4.00",
      msnfMin: "0.00",
      msnfMax: "2.00",
      otherSolidsMin: "0.00",
      otherSolidsMax: "5.00",
      totalSolidsMin: "15.00",
      totalSolidsMax: "25.00",
      podMin: "12.00",
      podMax: "17.00",
      fruitMin: "30.00",
      fruitMax: "60.00",
      alcoholMin: "1.00",
      alcoholMax: "2.00",
      overrunMin: "0.00",
      overrunMax: "15.00",
      groundFoodsMin: "0.00",
      groundFoodsMax: "0.00",
    },
    {
      name: "Gelato Vegano",
      sugarsMin: "16.00",
      sugarsMax: "22.00",
      fatsMin: "4.00",
      fatsMax: "12.00",
      msnfMin: "0.00",
      msnfMax: "0.50",
      otherSolidsMin: "6.00",
      otherSolidsMax: "16.00",
      totalSolidsMin: "35.00",
      totalSolidsMax: "40.00",
      podMin: "26.00",
      podMax: "31.00",
      fruitMin: "30.00",
      fruitMax: "60.00",
      alcoholMin: "1.00",
      alcoholMax: "2.00",
      overrunMin: "33.00",
      overrunMax: "35.00",
      groundFoodsMin: "5.00",
      groundFoodsMax: "10.00",
    },
    {
      name: "Gastronomico",
      sugarsMin: "14.00",
      sugarsMax: "22.00",
      fatsMin: "4.00",
      fatsMax: "15.00",
      msnfMin: "4.00",
      msnfMax: "10.00",
      otherSolidsMin: "0.00",
      otherSolidsMax: "15.00",
      totalSolidsMin: "25.00",
      totalSolidsMax: "50.00",
      podMin: "25.00",
      podMax: "31.00",
      fruitMin: "20.00",
      fruitMax: "40.00",
      alcoholMin: "1.00",
      alcoholMax: "2.00",
      overrunMin: "33.00",
      overrunMax: "35.00",
      groundFoodsMin: "5.00",
      groundFoodsMax: "10.00",
    },
    {
      name: "Personale 1",
      sugarsMin: "30.00",
      sugarsMax: "50.00",
      fatsMin: "0.00",
      fatsMax: "18.00",
      msnfMin: "0.00",
      msnfMax: "10.00",
      otherSolidsMin: "0.00",
      otherSolidsMax: "15.00",
      totalSolidsMin: "40.00",
      totalSolidsMax: "70.00",
      podMin: "40.00",
      podMax: "65.00",
      fruitMin: "30.00",
      fruitMax: "60.00",
      alcoholMin: "1.00",
      alcoholMax: "2.00",
      overrunMin: "33.00",
      overrunMax: "35.00",
      groundFoodsMin: "5.00",
      groundFoodsMax: "10.00",
    },
    {
      name: "Semilavorati",
      sugarsMin: "0.00",
      sugarsMax: "100.00",
      fatsMin: "0.00",
      fatsMax: "100.00",
      msnfMin: "0.00",
      msnfMax: "100.00",
      otherSolidsMin: "0.00",
      otherSolidsMax: "100.00",
      totalSolidsMin: "0.00",
      totalSolidsMax: "100.00",
      podMin: "0.00",
      podMax: "100.00",
      fruitMin: "0.00",
      fruitMax: "100.00",
      alcoholMin: "0.00",
      alcoholMax: "100.00",
      overrunMin: "0.00",
      overrunMax: "100.00",
      groundFoodsMin: "0.00",
      groundFoodsMax: "100.00",
    },
  ];

  try {
    // icecream categories
    await db.insert(iceCreamCategories).values(categories);
    // ingredients categories
    await db
      .insert(ingredientCategories)
      .values([
        { name: "Bevande" },
        { name: "Bevande Vegetali" },
        { name: "Infusi" },
        { name: "Olio & Aceto" },
        { name: "Cioccolato" },
        { name: "Alimenti Scatolati" },
        { name: "Spezie" },
        { name: "Alimenti in polvere" },
        { name: "Frutta Secca" },
        { name: "Creme & Paste" },
        { name: "Latticini & Uova" },
        { name: "Zuccheri" },
        { name: "Neutri & Basi" },
        { name: "Frutta" },
        { name: "Verdura" },
        { name: "Alcolici" },
        { name: "Salse" },
        { name: "Dolci" },
        { name: "Additivi Alimentari" },
        { name: "Gastronomico" },
        { name: "Fibre Vegetali" },
        { name: "Emulsionanti" },
        { name: "Personali" },
      ]);

    console.log("Seed completed successfully");
  } catch (error) {
    console.error("Error seeding database:", error);
  }
}

seed();
