import dotenv from "dotenv";
import { drizzle } from "drizzle-orm/neon-http";
import { ingredients } from "@/DB/schema";

dotenv.config({
  path: "./.env.local",
});

const db = drizzle(process.env.DATABASE_URL);

async function seedSweeteners() {
  const sweetenerIngredients = [
    {
      userId: "default",
      categoryId: 12,
      description: "Destrosio",
      sugar: "92.00",
      pac: "75.00",
      pod: "190.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Fruttosio",
      sugar: "100.00",
      pac: "0.00",
      pod: "173.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Glucosio",
      sugar: "100.00",
      pac: "100.00",
      pod: "74.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Saccarosio",
      sugar: "100.00",
      pac: "100.00",
      pod: "100.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Zucchero Invertito",
      sugar: "100.00",
      pac: "120.00",
      pod: "130.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sciroppo di Glucosio",
      sugar: "75.00",
      pac: "75.00",
      pod: "70.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Maltosio",
      sugar: "100.00",
      pac: "105.00",
      pod: "32.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Lattosio",
      sugar: "100.00",
      pac: "16.00",
      pod: "16.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Trehalosio",
      sugar: "100.00",
      pac: "40.00",
      pod: "40.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Isomalto",
      sugar: "0.00",
      pac: "5.00",
      pod: "10.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Eritritolo",
      sugar: "0.00",
      pac: "0.00",
      pod: "0.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Xilitolo",
      sugar: "0.00",
      pac: "0.00",
      pod: "-3.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sorbitolo",
      sugar: "0.00",
      pac: "0.00",
      pod: "50.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Mannitolo",
      sugar: "0.00",
      pac: "0.00",
      pod: "50.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Maltitolo",
      sugar: "0.00",
      pac: "52.00",
      pod: "35.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Lattitolo",
      sugar: "0.00",
      pac: "35.00",
      pod: "6.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sciroppo di Maltitolo",
      sugar: "0.00",
      pac: "52.00",
      pod: "35.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sciroppo di Sorbitolo",
      sugar: "0.00",
      pac: "0.00",
      pod: "50.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Glicerolo",
      sugar: "0.00",
      pac: "0.00",
      pod: "0.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Stevia",
      sugar: "0.00",
      pac: "0.00",
      pod: "200.00",
      minPercentage: "0.01",
      maxPercentage: "0.05",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Acesulfame K",
      sugar: "0.00",
      pac: "0.00",
      pod: "200.00",
      minPercentage: "0.01",
      maxPercentage: "0.05",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Aspartame",
      sugar: "0.00",
      pac: "0.00",
      pod: "200.00",
      minPercentage: "0.01",
      maxPercentage: "0.05",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Saccarina",
      sugar: "0.00",
      pac: "0.00",
      pod: "300.00",
      minPercentage: "0.01",
      maxPercentage: "0.05",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sucralosio",
      sugar: "0.00",
      pac: "0.00",
      pod: "600.00",
      minPercentage: "0.01",
      maxPercentage: "0.05",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Neotame",
      sugar: "0.00",
      pac: "0.00",
      pod: "8000.00",
      minPercentage: "0.01",
      maxPercentage: "0.05",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Advantame",
      sugar: "0.00",
      pac: "0.00",
      pod: "20000.00",
      minPercentage: "0.01",
      maxPercentage: "0.05",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sale",
      sugar: "0.00",
      pac: "0.00",
      pod: "0.00",
      minPercentage: "0.01",
      maxPercentage: "0.05",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
      bilanciaSuLiquidi: false, // Aggiunto questo campo
    },
  ];

  try {
    await db.insert(ingredients).values(sweetenerIngredients);
    console.log("Sweetener ingredients seeded successfully");
  } catch (error) {
    console.error("Error seeding sweetener ingredients:", error);
  }
}

seedSweeteners();

async function seedStabilizers() {
  const stabilizerIngredients = [
    {
      userId: "default",
      categoryId: 13,
      description: "Agar Agar",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.45",
      maxPercentage: "0.65",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Alginato di propilenglicole",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.35",
      maxPercentage: "0.45",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Base 100 - Valori Medi",
      sugar: "50.00",
      fat: "0.00",
      slng: "35.00",
      altriSolidi: "10.00",
      bilanciaSuLiquidi: true,
      pod: "70.00",
      pac: null,
      minPercentage: "9.00",
      maxPercentage: "11.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Base 150 - Valori Medi",
      sugar: "50.00",
      fat: "0.00",
      slng: "40.00",
      altriSolidi: "7.00",
      bilanciaSuLiquidi: true,
      pod: "70.00",
      pac: null,
      minPercentage: "14.00",
      maxPercentage: "15.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Base 50 - Valori Medi",
      sugar: "55.00",
      fat: "0.00",
      slng: "20.00",
      altriSolidi: "20.00",
      bilanciaSuLiquidi: true,
      pod: "77.00",
      pac: null,
      minPercentage: "4.00",
      maxPercentage: "6.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Carbossimetilcellulosa (CMC)",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.05",
      maxPercentage: "0.15",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Farina di semi di carrube",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.35",
      maxPercentage: "0.55",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Farina di semi di guar",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.10",
      maxPercentage: "0.25",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Farina di semi di tara",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.25",
      maxPercentage: "0.40",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Gomma di Xantano",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.05",
      maxPercentage: "0.15",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Cioccolato Tara",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.25",
      maxPercentage: "0.45",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Crema Carruba/Guar",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.15",
      maxPercentage: "0.45",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Frutta Tara/Guar (Polpa)",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.15",
      maxPercentage: "0.35",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Frutta Tara/Guar (Succhi)",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.25",
      maxPercentage: "0.45",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Vegan Creme",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.40",
      maxPercentage: "0.55",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Sorbetti Grassi",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "0.25",
      maxPercentage: "0.35",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Amido di mais",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: null,
      minPercentage: "2.50",
      maxPercentage: "4.50",
      foodCostForKg: null,
    },
  ];

  try {
    await db.insert(ingredients).values(stabilizerIngredients);
    console.log("Stabilizer ingredients seeded successfully");
  } catch (error) {
    console.error("Error seeding stabilizer ingredients:", error);
  }
}

seedStabilizers();

async function seedIngredientsCategoryAlimenti() {
  const ingredientsData = [
    {
      userId: "default",
      categoryId: 4,
      description: "Aceto di Mele",
      sugar: "0.40",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "4.00",
      bilanciaSuLiquidi: false,
      pod: "0.40",
      pac: "1.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 19,
      description: "Acido citrico",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 1,
      description: "Acqua",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 1,
      description: "Acqua di cottura",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "5.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 14,
      description: "Avocado",
      sugar: "1.80",
      fat: "23.00",
      slng: "0.00",
      altriSolidi: "7.70",
      bilanciaSuLiquidi: false,
      pod: "1.80",
      pac: "1.80",
      minPercentage: "15.00",
      maxPercentage: "35.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 7,
      description: "Baccello di vaniglia",
      sugar: "15.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "35.00",
      bilanciaSuLiquidi: false,
      pod: "15.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 7,
      description: "Basilico",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: "0.50",
      maxPercentage: "1.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 19,
      description: "Bicarbonato di sodio",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "98.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 20,
      description: "Bisque di gamberi",
      sugar: "0.00",
      fat: "2.00",
      slng: "0.00",
      altriSolidi: "4.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 4,
      description: "Burro di cacao",
      sugar: "0.00",
      fat: "100.00",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "-72.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 8,
      description: "Cacao in polvere 11% Mat. Grassa",
      sugar: "0.00",
      fat: "11.00",
      slng: "0.00",
      altriSolidi: "89.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "-15.40",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 8,
      description: "Cacao in polvere 22% Mat. Grassa",
      sugar: "0.00",
      fat: "22.00",
      slng: "0.00",
      altriSolidi: "78.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "-30.80",
      minPercentage: "3.00",
      maxPercentage: "6.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 3,
      description: "Caffè (espresso)",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.20",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 8,
      description: "Caffè liofilizzato",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 4,
      description: "Camomilla",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 7,
      description: "Cannella",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 9,
      description: "Castagne Precotte",
      sugar: "7.10",
      fat: "2.00",
      slng: "0.00",
      altriSolidi: "39.00",
      bilanciaSuLiquidi: false,
      pod: "7.10",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 7,
      description: "Chiodi di Garofano",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 5,
      description: "Cioccolato al latte 35%",
      sugar: "40.00",
      fat: "35.00",
      slng: "14.00",
      altriSolidi: "11.00",
      bilanciaSuLiquidi: false,
      pod: "40.00",
      pac: "-9.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 5,
      description: "Cioccolato al latte 40%",
      sugar: "35.00",
      fat: "40.00",
      slng: "20.00",
      altriSolidi: "5.00",
      bilanciaSuLiquidi: false,
      pod: "35.00",
      pac: "-21.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 5,
      description: "Cioccolato bianco",
      sugar: "45.00",
      fat: "40.00",
      slng: "15.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "45.00",
      pac: "-11.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 5,
      description: "Cioccolato fondente 55%",
      sugar: "45.00",
      fat: "35.00",
      slng: "0.00",
      altriSolidi: "20.00",
      bilanciaSuLiquidi: false,
      pod: "45.00",
      pac: "-4.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 5,
      description: "Cioccolato fondente 60%",
      sugar: "40.00",
      fat: "38.00",
      slng: "0.00",
      altriSolidi: "22.00",
      bilanciaSuLiquidi: false,
      pod: "40.00",
      pac: "-13.20",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 5,
      description: "Cioccolato fondente 65%",
      sugar: "35.00",
      fat: "40.00",
      slng: "0.00",
      altriSolidi: "25.00",
      bilanciaSuLiquidi: false,
      pod: "35.00",
      pac: "-21.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 5,
      description: "Cioccolato fondente 70%",
      sugar: "30.00",
      fat: "42.50",
      slng: "0.00",
      altriSolidi: "27.50",
      bilanciaSuLiquidi: false,
      pod: "30.00",
      pac: "-29.50",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 5,
      description: "Cioccolato fondente 80%",
      sugar: "20.00",
      fat: "49.00",
      slng: "0.00",
      altriSolidi: "31.00",
      bilanciaSuLiquidi: false,
      pod: "20.00",
      pac: "-48.60",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Crema pan di stelle",
      sugar: "51.00",
      fat: "30.20",
      slng: "8.30",
      altriSolidi: "1.00",
      bilanciaSuLiquidi: false,
      pod: "51.00",
      pac: "51.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 18,
      description: "Dulce de leche",
      sugar: "50.00",
      fat: "7.00",
      slng: "7.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "50.00",
      pac: "50.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 20,
      description: "Estratto di Mais CBT",
      sugar: "4.50",
      fat: "1.50",
      slng: "0.00",
      altriSolidi: "10.00",
      bilanciaSuLiquidi: false,
      pod: "4.50",
      pac: "4.50",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 6,
      description: "Funghi",
      sugar: "1.00",
      fat: "0.50",
      slng: "0.00",
      altriSolidi: "6.50",
      bilanciaSuLiquidi: false,
      pod: "1.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 3,
      description: "Infuso di erbe aromatiche",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 3,
      description: "Infuso di sambuco",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "5.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 21,
      description: "Inulina",
      sugar: "25.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "75.00",
      bilanciaSuLiquidi: false,
      pod: "25.00",
      pac: "25.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 18,
      description: "Latte al pandoro",
      sugar: "6.00",
      fat: "8.00",
      slng: "6.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "6.00",
      pac: "6.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 18,
      description: "Latte al panettone",
      sugar: "8.00",
      fat: "4.00",
      slng: "6.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "8.00",
      pac: "8.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 2,
      description: "Latte di Anacardi",
      sugar: "2.40",
      fat: "2.50",
      slng: "0.00",
      altriSolidi: "4.80",
      bilanciaSuLiquidi: false,
      pod: "2.40",
      pac: "2.40",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 2,
      description: "Latte di Cocco (Bevanda)",
      sugar: "1.90",
      fat: "3.40",
      slng: "0.00",
      altriSolidi: "1.00",
      bilanciaSuLiquidi: false,
      pod: "1.90",
      pac: "1.90",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 2,
      description: "Latte di Cocco Thai",
      sugar: "2.00",
      fat: "17.40",
      slng: "0.00",
      altriSolidi: "2.00",
      bilanciaSuLiquidi: false,
      pod: "2.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 2,
      description: "Latte di Mandorla",
      sugar: "1.70",
      fat: "1.60",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "1.70",
      pac: "1.70",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 2,
      description: "Latte di Riso",
      sugar: "2.00",
      fat: "2.50",
      slng: "0.00",
      altriSolidi: "8.00",
      bilanciaSuLiquidi: false,
      pod: "2.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 2,
      description: "Latte di Soia",
      sugar: "4.50",
      fat: "3.40",
      slng: "0.00",
      altriSolidi: "2.80",
      bilanciaSuLiquidi: false,
      pod: "4.50",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 22,
      description: "Lecitina di soia",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 8,
      description: "Liquirizia in polvere",
      sugar: "20.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "80.00",
      bilanciaSuLiquidi: false,
      pod: "20.00",
      pac: "20.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 9,
      description: "Mandorle pelate",
      sugar: "3.50",
      fat: "54.00",
      slng: "0.00",
      altriSolidi: "38.00",
      bilanciaSuLiquidi: false,
      pod: "3.50",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 11,
      description: "Margarina vegetale",
      sugar: "0.00",
      fat: "84.00",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Massa di cacao 100%",
      sugar: "1.00",
      fat: "54.00",
      slng: "0.00",
      altriSolidi: "45.00",
      bilanciaSuLiquidi: false,
      pod: "1.00",
      pac: "-74.60",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 18,
      description: "Meringa",
      sugar: "94.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "6.00",
      bilanciaSuLiquidi: false,
      pod: "94.00",
      pac: "94.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Nutella",
      sugar: "56.80",
      fat: "31.60",
      slng: "6.00",
      altriSolidi: "5.60",
      bilanciaSuLiquidi: false,
      pod: "56.80",
      pac: "12.60",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 4,
      description: "Olio d'Argan",
      sugar: "0.00",
      fat: "98.00",
      slng: "0.00",
      altriSolidi: "2.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 4,
      description: "Olio di cocco",
      sugar: "0.00",
      fat: "100.00",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "-50.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 4,
      description: "Olio di semi di girasole",
      sugar: "0.00",
      fat: "100.00",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "34.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 4,
      description: "Olio d'oliva",
      sugar: "0.00",
      fat: "98.00",
      slng: "0.00",
      altriSolidi: "2.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "12.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 8,
      description: "Ovomaltina",
      sugar: "16.00",
      fat: "3.60",
      slng: "0.00",
      altriSolidi: "15.00",
      bilanciaSuLiquidi: false,
      pod: "16.00",
      pac: "16.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 18,
      description: "Panettone",
      sugar: "32.00",
      fat: "13.00",
      slng: "0.00",
      altriSolidi: "29.60",
      bilanciaSuLiquidi: false,
      pod: "32.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 11,
      description: "Panna vegetale",
      sugar: "1.20",
      fat: "14.00",
      slng: "0.00",
      altriSolidi: "2.50",
      bilanciaSuLiquidi: false,
      pod: "1.20",
      pac: "1.20",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di anacardi",
      sugar: "6.30",
      fat: "49.00",
      slng: "0.00",
      altriSolidi: "32.00",
      bilanciaSuLiquidi: false,
      pod: "6.30",
      pac: "0.00",
      minPercentage: "6.00",
      maxPercentage: "12.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di arachidi",
      sugar: "0.00",
      fat: "50.00",
      slng: "0.00",
      altriSolidi: "50.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: "6.00",
      maxPercentage: "12.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di caffé tostato",
      sugar: "0.00",
      fat: "14.00",
      slng: "0.00",
      altriSolidi: "86.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di gianduia",
      sugar: "40.00",
      fat: "30.00",
      slng: "0.00",
      altriSolidi: "30.00",
      bilanciaSuLiquidi: false,
      pod: "40.00",
      pac: "-2.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di malaga",
      sugar: "55.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "35.00",
      bilanciaSuLiquidi: false,
      pod: "55.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di mandorle",
      sugar: "5.00",
      fat: "60.00",
      slng: "0.00",
      altriSolidi: "23.00",
      bilanciaSuLiquidi: false,
      pod: "5.00",
      pac: "0.00",
      minPercentage: "6.00",
      maxPercentage: "12.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di More",
      sugar: "60.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "35.00",
      bilanciaSuLiquidi: false,
      pod: "60.00",
      pac: "60.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di nocciole",
      sugar: "0.00",
      fat: "65.00",
      slng: "0.00",
      altriSolidi: "35.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: "6.00",
      maxPercentage: "12.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di noci",
      sugar: "0.00",
      fat: "64.00",
      slng: "0.00",
      altriSolidi: "36.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: "6.00",
      maxPercentage: "12.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di pinoli",
      sugar: "0.00",
      fat: "62.00",
      slng: "0.00",
      altriSolidi: "38.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: "6.00",
      maxPercentage: "12.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di pistacchio",
      sugar: "0.00",
      fat: "50.00",
      slng: "0.00",
      altriSolidi: "50.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: "6.00",
      maxPercentage: "12.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di torrone",
      sugar: "40.00",
      fat: "35.00",
      slng: "0.00",
      altriSolidi: "25.00",
      bilanciaSuLiquidi: false,
      pod: "40.00",
      pac: "-9.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di vaniglia",
      sugar: "65.00",
      fat: "2.00",
      slng: "0.00",
      altriSolidi: "28.00",
      bilanciaSuLiquidi: false,
      pod: "65.00",
      pac: "62.20",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 10,
      description: "Pasta di zabaione",
      sugar: "55.00",
      fat: "10.00",
      slng: "0.00",
      altriSolidi: "25.00",
      bilanciaSuLiquidi: false,
      pod: "55.00",
      pac: "41.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 7,
      description: "Pepe bianco macinato",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 7,
      description: "Pepe nero macinato",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 7,
      description: "Sale",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "100.00",
      minPercentage: "0.00",
      maxPercentage: "0.80",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 17,
      description: "Salsa al curry",
      sugar: "3.50",
      fat: "27.50",
      slng: "3.70",
      altriSolidi: "6.60",
      bilanciaSuLiquidi: false,
      pod: "3.50",
      pac: "6.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 17,
      description: "Salsa di datterini gialli",
      sugar: "4.00",
      fat: "3.50",
      slng: "0.00",
      altriSolidi: "15.50",
      bilanciaSuLiquidi: false,
      pod: "4.00",
      pac: "4.20",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 1,
      description: "Sciroppo di Sambuco",
      sugar: "32.80",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "3.60",
      bilanciaSuLiquidi: false,
      pod: "32.80",
      pac: "32.80",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 14,
      description: "Scorza di Arancia",
      sugar: "4.00",
      fat: "0.30",
      slng: "0.00",
      altriSolidi: "5.00",
      bilanciaSuLiquidi: false,
      pod: "4.00",
      pac: "4.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 14,
      description: "Scorza di Limone",
      sugar: "4.00",
      fat: "0.30",
      slng: "0.00",
      altriSolidi: "5.00",
      bilanciaSuLiquidi: false,
      pod: "4.00",
      pac: "4.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 9,
      description: "Semi di Senape",
      sugar: "7.00",
      fat: "37.00",
      slng: "0.00",
      altriSolidi: "51.00",
      bilanciaSuLiquidi: false,
      pod: "7.00",
      pac: "5.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 17,
      description: "Senape",
      sugar: "1.00",
      fat: "4.00",
      slng: "0.00",
      altriSolidi: "10.00",
      bilanciaSuLiquidi: false,
      pod: "1.00",
      pac: "10.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 7,
      description: "Spezie secche in polvere",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 3,
      description: "Tè verde",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "0.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 7,
      description: "Zafferano",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      bilanciaSuLiquidi: false,
      pod: "0.00",
      pac: "0.00",
      minPercentage: null,
      maxPercentage: null,
      foodCostForKg: null,
    },
  ];

  try {
    await db.insert(ingredients).values(ingredientsData);
    console.log("Ingredients for category Alimenti seeded successfully");
  } catch (error) {
    console.error("Error seeding ingredients for category Alimenti:", error);
  }
}

seedIngredientsCategoryAlimenti();
