import dotenv from "dotenv";
import { drizzle } from "drizzle-orm/neon-http";
import {ingredients} from "@/DB/schema";

dotenv.config({
  path: "./.env.local",
});

const db = drizzle(process.env.DATABASE_URL);

async function seedSweeteners() {
  const sweetenerIngredients = [
    {
      userId: "default",
      categoryId: 12,
      description: "Destrosio",
      sugar: "92.00",
      pac: "75.00",
      pod: "190.00",
      minPercentage: "4.00",
      maxPercentage: "10.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Eritritolo",
      sugar: "100.00",
      pac: "65.00",
      pod: "280.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Fruttosio",
      sugar: "99.00",
      pac: "140.00",
      pod: "190.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Glicirizzina",
      sugar: "100.00",
      pac: "5000.00",
      pod: "42.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Glucosio atomizzato 21 DE",
      sugar: "95.00",
      pac: "10.00",
      pod: "35.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Glucosio atomizzato 39 DE",
      sugar: "95.00",
      pac: "23.00",
      pod: "45.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Glucosio atomizzato 42 DE",
      sugar: "95.00",
      pac: "50.00",
      pod: "70.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Glucosio atomizzato 52 DE",
      sugar: "95.00",
      pac: "58.00",
      pod: "87.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Isoglucosio",
      sugar: "100.00",
      pac: "130.00",
      pod: "190.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Lattosio",
      sugar: "100.00",
      pac: "10.00",
      pod: "100.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Maltitolo",
      sugar: "100.00",
      pac: "90.00",
      pod: "100.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Maltodestrina 5 DE",
      sugar: "95.00",
      pac: "5.00",
      pod: "9.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Maltodestrina 18 DE",
      sugar: "95.00",
      pac: "13.00",
      pod: "32.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Maltodestrina 20 DE",
      sugar: "95.00",
      pac: "18.00",
      pod: "37.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Maltosio",
      sugar: "100.00",
      pac: "32.00",
      pod: "100.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Mannitolo",
      sugar: "100.00",
      pac: "50.00",
      pod: "188.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Miele",
      sugar: "82.00",
      pac: "130.00",
      pod: "190.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Saccarosio",
      sugar: "100.00",
      pac: "100.00",
      pod: "100.00",
      minPercentage: "8.00",
      maxPercentage: "15.00",
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sciroppo di glucosio 30 DE",
      sugar: "80.00",
      pac: "23.00",
      pod: "42.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sciroppo di glucosio 38 DE",
      sugar: "80.00",
      pac: "29.00",
      pod: "55.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sciroppo di glucosio 44DE",
      sugar: "80.00",
      pac: "52.00",
      pod: "90.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sciroppo di glucosio 62DE",
      sugar: "80.00",
      pac: "64.00",
      pod: "120.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Sorbitolo",
      sugar: "100.00",
      pac: "60.00",
      pod: "190.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Stevia",
      sugar: "100.00",
      pac: "30000.00",
      pod: "0.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Tagatosio",
      sugar: "100.00",
      pac: "90.00",
      pod: "190.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Trealosio",
      sugar: "96.00",
      pac: "45.00",
      pod: "100.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Xilitolo",
      sugar: "100.00",
      pac: "100.00",
      pod: "225.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 12,
      description: "Zucchero Invertito",
      sugar: "70.00",
      pac: "125.00",
      pod: "190.00",
      minPercentage: null,
      maxPercentage: null,
      fat: null,
      slng: null,
      altriSolidi: null,
      foodCostForKg: null,
    },
  ]

  try {
    await db.insert(ingredients).values(sweetenerIngredients)
    console.log("Sweetener ingredients seeded successfully")
  } catch (error) {
    console.error("Error seeding sweetener ingredients:", error)
  }
}

seedSweeteners();


async function seedStabilizers() {
  const stabilizerIngredients = [
    {
      userId: "default",
      categoryId: 13,
      description: "Agar Agar",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.45",
      maxPercentage: "0.65",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Alginato di propilenglicole",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.35",
      maxPercentage: "0.45",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Base 100 - Valori Medi",
      sugar: "50.00",
      fat: "0.00",
      slng: "35.00",
      altriSolidi: "10.00",
      pod: "70.00",
      pac: null,
      minPercentage: "9.00",
      maxPercentage: "11.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Base 150 - Valori Medi",
      sugar: "50.00",
      fat: "0.00",
      slng: "40.00",
      altriSolidi: "7.00",
      pod: "70.00",
      pac: null,
      minPercentage: "14.00",
      maxPercentage: "15.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Base 50 - Valori Medi",
      sugar: "55.00",
      fat: "0.00",
      slng: "20.00",
      altriSolidi: "20.00",
      pod: "77.00",
      pac: null,
      minPercentage: "4.00",
      maxPercentage: "6.00",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Carbossimetilcellulosa (CMC)",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.05",
      maxPercentage: "0.15",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Farina di semi di carrube",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.35",
      maxPercentage: "0.55",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Farina di semi di guar",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.10",
      maxPercentage: "0.25",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Farina di semi di tara",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.25",
      maxPercentage: "0.40",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Gomma di Xantano",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.05",
      maxPercentage: "0.15",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Cioccolato Tara",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.25",
      maxPercentage: "0.45",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Crema Carruba/Guar",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.15",
      maxPercentage: "0.45",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Frutta Tara/Guar (Polpa)",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.15",
      maxPercentage: "0.35",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Frutta Tara/Guar (Succhi)",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.25",
      maxPercentage: "0.45",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Vegan Creme",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.40",
      maxPercentage: "0.55",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Neutro Sorbetti Grassi",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "0.25",
      maxPercentage: "0.35",
      foodCostForKg: null,
    },
    {
      userId: "default",
      categoryId: 13,
      description: "Amido di mais",
      sugar: "0.00",
      fat: "0.00",
      slng: "0.00",
      altriSolidi: "100.00",
      pod: "0.00",
      pac: null,
      minPercentage: "2.50",
      maxPercentage: "4.50",
      foodCostForKg: null,
    },
  ]

  try {
    await db.insert(ingredients).values(stabilizerIngredients)
    console.log("Stabilizer ingredients seeded successfully")
  } catch (error) {
    console.error("Error seeding stabilizer ingredients:", error)
  }
}

seedStabilizers()
